name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. JDK 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      # 3. Gradle 빌드 및 테스트
      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}  # GitHub Secrets에서 가져온 사용자명
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}  # GitHub Secrets에서 가져온 비밀번호
          JWT_SECRET: ${{ secrets.JWT_SECRET }}               # JWT 비밀
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}     # OpenAI API 키
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}     # AWS 액세스 키
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}     # AWS 비밀 키
          KAKAO_CLIENT_ID: ${{ secrets.KAKAO_CLIENT_ID }}   # Kakao 클라이언트 ID
        run: ./gradlew clean bootjar

      # 4. Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # 5. 도커 이미지 빌드
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/publicplace_be:latest .

      # 6. 도커 이미지 푸시
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/publicplace_be:latest

      # 7. AWS EC2에 SSH 접속하여 도커 컨테이너 업데이트
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/publicplace_be:latest
            docker stop publicplace_be || true
            docker rm publicplace_be || true
            docker run -d --name publicplace_be -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/publicplace_be:latest
